/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * No documentation available
 *
 * @param ASSET_TRANSACTION
 */

data class AssetTransactions(

    @field:JsonProperty("ASSET_TRANSACTION")
    val ASSET_TRANSACTION: kotlin.collections.List<AssetTransaction>

) : kotlin.collections.HashMap<String, kotlin.Any>()

