/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * An object containing identifying numbers used for making electronic transfers to and from the `accounts`. The identifying number type (ACH, EFT, IBAN, or BACS) used will depend on the country of the account. An account may have more than one number type. If a particular identifying number type is not used by any `accounts` for which data has been requested, the array for that type will be empty.
 *
 * @param ach An array of ACH numbers identifying accounts.
 * @param eft An array of EFT numbers identifying accounts.
 * @param international An array of IBAN numbers identifying accounts.
 * @param bacs An array of BACS numbers identifying accounts.
 */

data class AuthGetNumbers(

    /* An array of ACH numbers identifying accounts. */
    @field:JsonProperty("ach")
    val ach: kotlin.collections.List<NumbersACH>,

    /* An array of EFT numbers identifying accounts. */
    @field:JsonProperty("eft")
    val eft: kotlin.collections.List<NumbersEFT>,

    /* An array of IBAN numbers identifying accounts. */
    @field:JsonProperty("international")
    val international: kotlin.collections.List<NumbersInternational>,

    /* An array of BACS numbers identifying accounts. */
    @field:JsonProperty("bacs")
    val bacs: kotlin.collections.List<NumbersBACS>

) : kotlin.collections.HashMap<String, kotlin.Any>()

