/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Information about the balance of a bank transfer
 *
 * @param available The total available balance - the sum of all successful debit transfer amounts minus all credit transfer amounts.
 * @param transactable The transactable balance shows the amount in your account that you are able to use for transfers, and is essentially your available balance minus your minimum balance.
 */

data class BankTransferBalance(

    /* The total available balance - the sum of all successful debit transfer amounts minus all credit transfer amounts. */
    @field:JsonProperty("available")
    val available: kotlin.String,

    /* The transactable balance shows the amount in your account that you are able to use for transfers, and is essentially your available balance minus your minimum balance. */
    @field:JsonProperty("transactable")
    val transactable: kotlin.String

) : kotlin.collections.HashMap<String, kotlin.Any>()

