/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Defines the request schema for `/bank_transfer/event/list`
 *
 * @param clientId Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
 * @param secret Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
 * @param startDate The start datetime of bank transfers to list. This should be in RFC 3339 format (i.e. `2019-12-06T22:35:49Z`)
 * @param endDate The end datetime of bank transfers to list. This should be in RFC 3339 format (i.e. `2019-12-06T22:35:49Z`)
 * @param bankTransferId Plaid’s unique identifier for a bank transfer.
 * @param accountId The account ID to get events for all transactions to/from an account.
 * @param bankTransferType
 * @param eventTypes Filter events by event type.
 * @param count The maximum number of bank transfer events to return. If the number of events matching the above parameters is greater than `count`, the most recent events will be returned.
 * @param offset The offset into the list of bank transfer events. When `count`=25 and `offset`=0, the first 25 events will be returned. When `count`=25 and `offset`=25, the next 25 bank transfer events will be returned.
 * @param originationAccountId The origination account ID to get events for transfers from a specific origination account.
 * @param direction
 */

data class BankTransferEventListRequest(

    /* Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
    @field:JsonProperty("client_id")
    val clientId: kotlin.String? = null,

    /* Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
    @field:JsonProperty("secret")
    val secret: kotlin.String? = null,

    /* The start datetime of bank transfers to list. This should be in RFC 3339 format (i.e. `2019-12-06T22:35:49Z`) */
    @field:JsonProperty("start_date")
    val startDate: java.time.OffsetDateTime? = null,

    /* The end datetime of bank transfers to list. This should be in RFC 3339 format (i.e. `2019-12-06T22:35:49Z`) */
    @field:JsonProperty("end_date")
    val endDate: java.time.OffsetDateTime? = null,

    /* Plaid’s unique identifier for a bank transfer. */
    @field:JsonProperty("bank_transfer_id")
    val bankTransferId: kotlin.String? = null,

    /* The account ID to get events for all transactions to/from an account. */
    @field:JsonProperty("account_id")
    val accountId: kotlin.String? = null,

    @field:JsonProperty("bank_transfer_type")
    val bankTransferType: BankTransferEventListBankTransferType? = null,

    /* Filter events by event type. */
    @field:JsonProperty("event_types")
    val eventTypes: kotlin.collections.List<BankTransferEventType>? = null,

    /* The maximum number of bank transfer events to return. If the number of events matching the above parameters is greater than `count`, the most recent events will be returned. */
    @field:JsonProperty("count")
    val count: kotlin.Int? = 25,

    /* The offset into the list of bank transfer events. When `count`=25 and `offset`=0, the first 25 events will be returned. When `count`=25 and `offset`=25, the next 25 bank transfer events will be returned. */
    @field:JsonProperty("offset")
    val offset: kotlin.Int? = 0,

    /* The origination account ID to get events for transfers from a specific origination account. */
    @field:JsonProperty("origination_account_id")
    val originationAccountId: kotlin.String? = null,

    @field:JsonProperty("direction")
    val direction: BankTransferEventListDirection? = null

)

