/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Information describing a transaction category
 *
 * @param categoryId An identifying number for the category. `category_id` is a Plaid-specific identifier and does not necessarily correspond to merchant category codes.
 * @param group `place` for physical transactions or `special` for other transactions such as bank charges.
 * @param hierarchy A hierarchical array of the categories to which this `category_id` belongs.
 */

data class Category(

    /* An identifying number for the category. `category_id` is a Plaid-specific identifier and does not necessarily correspond to merchant category codes. */
    @field:JsonProperty("category_id")
    val categoryId: kotlin.String,

    /* `place` for physical transactions or `special` for other transactions such as bank charges. */
    @field:JsonProperty("group")
    val group: kotlin.String,

    /* A hierarchical array of the categories to which this `category_id` belongs. */
    @field:JsonProperty("hierarchy")
    val hierarchy: kotlin.collections.List<kotlin.String>

) : kotlin.collections.HashMap<String, kotlin.Any>()

