/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * A client-provided transaction for Plaid to enhance.
 *
 * @param id Unique transaction identifier to tie transactions back to clients' systems.
 * @param description The raw description of the transaction.
 * @param amount The value of the transaction, denominated in the account's currency, as stated in `iso_currency_code`. Positive values when money moves out of the account; negative values when money moves in. For example, debit card purchases are positive; credit card payments, direct deposits, and refunds are negative.
 * @param isoCurrencyCode The ISO-4217 currency code of the transaction.
 */

data class ClientProvidedRawTransaction(

    /* Unique transaction identifier to tie transactions back to clients' systems. */
    @field:JsonProperty("id")
    val id: kotlin.String,

    /* The raw description of the transaction. */
    @field:JsonProperty("description")
    val description: kotlin.String,

    /* The value of the transaction, denominated in the account's currency, as stated in `iso_currency_code`. Positive values when money moves out of the account; negative values when money moves in. For example, debit card purchases are positive; credit card payments, direct deposits, and refunds are negative. */
    @field:JsonProperty("amount")
    val amount: kotlin.Double,

    /* The ISO-4217 currency code of the transaction. */
    @field:JsonProperty("iso_currency_code")
    val isoCurrencyCode: kotlin.String

) : kotlin.collections.HashMap<String, kotlin.Any>()

