/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * ISO-3166-1 alpha-2 country code standard.
 *
 * Values: uS,gB,eS,nL,fR,iE,cA,dE,iT
 */

enum class CountryCode(val value: kotlin.String) {

    @JsonProperty(value = "US")
    uS("US"),

    @JsonProperty(value = "GB")
    gB("GB"),

    @JsonProperty(value = "ES")
    eS("ES"),

    @JsonProperty(value = "NL")
    nL("NL"),

    @JsonProperty(value = "FR")
    fR("FR"),

    @JsonProperty(value = "IE")
    iE("IE"),

    @JsonProperty(value = "CA")
    cA("CA"),

    @JsonProperty(value = "DE")
    dE("DE"),

    @JsonProperty(value = "IT")
    iT("IT");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CountryCode) "$data" else null

        /**
         * Returns a valid [CountryCode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CountryCode? = data?.let {
            val normalizedData = "$it".lowercase()
            values().firstOrNull { value ->
                it == value || normalizedData == "$value".lowercase()
            }
        }
    }
}

