/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The object containing proof of employment data for an individual.
 *
 * @param accountId ID of the payroll provider account.
 * @param status Current employment status.
 * @param startDate Start of employment in ISO 8601 format (YYYY-MM-DD).
 * @param endDate End of employment, if applicable. Provided in ISO 8601 format (YYY-MM-DD).
 * @param employer
 * @param title Current title of employee.
 * @param platformIds
 * @param employeeType The type of employment for the individual. `\"FULL_TIME\"`: A full-time employee. `\"PART_TIME\"`: A part-time employee. `\"CONTRACTOR\"`: An employee typically hired externally through a contracting group. `\"TEMPORARY\"`: A temporary employee. `\"OTHER\"`: The employee type is not one of the above defined types.
 * @param lastPaystubDate The date of the employee's most recent paystub in ISO 8601 format (YYYY-MM-DD).
 */

data class CreditEmploymentVerification(

    /* ID of the payroll provider account. */
    @field:JsonProperty("account_id")
    val accountId: kotlin.String?,

    /* Current employment status. */
    @field:JsonProperty("status")
    val status: kotlin.String?,

    /* Start of employment in ISO 8601 format (YYYY-MM-DD). */
    @field:JsonProperty("start_date")
    val startDate: java.time.LocalDate?,

    /* End of employment, if applicable. Provided in ISO 8601 format (YYY-MM-DD). */
    @field:JsonProperty("end_date")
    val endDate: java.time.LocalDate?,

    @field:JsonProperty("employer")
    val employer: CreditEmployerVerification,

    /* Current title of employee. */
    @field:JsonProperty("title")
    val title: kotlin.String?,

    @field:JsonProperty("platform_ids")
    val platformIds: CreditPlatformIds,

    /* The type of employment for the individual. `\"FULL_TIME\"`: A full-time employee. `\"PART_TIME\"`: A part-time employee. `\"CONTRACTOR\"`: An employee typically hired externally through a contracting group. `\"TEMPORARY\"`: A temporary employee. `\"OTHER\"`: The employee type is not one of the above defined types. */
    @field:JsonProperty("employee_type")
    val employeeType: kotlin.String?,

    /* The date of the employee's most recent paystub in ISO 8601 format (YYYY-MM-DD). */
    @field:JsonProperty("last_paystub_date")
    val lastPaystubDate: java.time.LocalDate?

) : kotlin.collections.HashMap<String, kotlin.Any>()

