/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * An object with the deduction information found on a paystub.
 *
 * @param breakdown
 * @param total
 * @param subtotals
 * @param totals
 */

data class Deductions(

    @field:JsonProperty("breakdown")
    val breakdown: kotlin.collections.List<DeductionsBreakdown>,

    @field:JsonProperty("total")
    val total: DeductionsTotal,

    @field:JsonProperty("subtotals")
    @Deprecated(message = "This property is deprecated.")
    val subtotals: kotlin.collections.List<Total>? = null,

    @field:JsonProperty("totals")
    @Deprecated(message = "This property is deprecated.")
    val totals: kotlin.collections.List<Total>? = null

) : kotlin.collections.HashMap<String, kotlin.Any>()

