/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Information associated with the entity watchlist hit
 *
 * @param documents Documents associated with the watchlist hit
 * @param emailAddresses Email addresses associated with the watchlist hit
 * @param locations Locations associated with the watchlist hit
 * @param names Names associated with the watchlist hit
 * @param phoneNumbers Phone numbers associated with the watchlist hit
 * @param urls URLs associated with the watchlist hit
 */

data class EntityScreeningHitData(

    /* Documents associated with the watchlist hit */
    @field:JsonProperty("documents")
    val documents: kotlin.collections.List<EntityScreeningHitDocumentsItems>? = null,

    /* Email addresses associated with the watchlist hit */
    @field:JsonProperty("email_addresses")
    val emailAddresses: kotlin.collections.List<EntityScreeningHitEmailsItems>? = null,

    /* Locations associated with the watchlist hit */
    @field:JsonProperty("locations")
    val locations: kotlin.collections.List<GenericScreeningHitLocationItems>? = null,

    /* Names associated with the watchlist hit */
    @field:JsonProperty("names")
    val names: kotlin.collections.List<EntityScreeningHitNamesItems>? = null,

    /* Phone numbers associated with the watchlist hit */
    @field:JsonProperty("phone_numbers")
    val phoneNumbers: kotlin.collections.List<EntityScreeningHitsPhoneNumberItems>? = null,

    /* URLs associated with the watchlist hit */
    @field:JsonProperty("urls")
    val urls: kotlin.collections.List<EntityScreeningHitUrlsItems>? = null

)

