/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The entity screening object allows you to represent an entity in your system, update its profile, and search for it on various watchlists. Note: Rejected entity screenings will not receive new hits, regardless of entity program configuration.
 *
 * @param id ID of the associated entity screening.
 * @param searchTerms
 * @param assignee
 * @param status
 * @param clientUserId
 * @param auditTrail
 * @param requestId A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
 */

data class EntityWatchlistScreeningResponse(

    /* ID of the associated entity screening. */
    @field:JsonProperty("id")
    val id: kotlin.String,

    @field:JsonProperty("search_terms")
    val searchTerms: EntityWatchlistScreeningSearchTerms,

    @field:JsonProperty("assignee")
    val assignee: kotlin.String?,

    @field:JsonProperty("status")
    val status: WatchlistScreeningStatus,

    @field:JsonProperty("client_user_id")
    val clientUserId: kotlin.String?,

    @field:JsonProperty("audit_trail")
    val auditTrail: WatchlistScreeningAuditTrail,

    /* A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
    @field:JsonProperty("request_id")
    val requestId: kotlin.String

) : kotlin.collections.HashMap<String, kotlin.Any>()

