/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The status of a step in the identity verification process.
 *
 * Values: success,active,failed,waitingForPrerequisite,notApplicable,skipped,expired,canceled,pendingReview,manuallyApproved,manuallyRejected
 */

enum class IdentityVerificationStepStatus(val value: kotlin.String) {

    @JsonProperty(value = "success")
    success("success"),

    @JsonProperty(value = "active")
    active("active"),

    @JsonProperty(value = "failed")
    failed("failed"),

    @JsonProperty(value = "waiting_for_prerequisite")
    waitingForPrerequisite("waiting_for_prerequisite"),

    @JsonProperty(value = "not_applicable")
    notApplicable("not_applicable"),

    @JsonProperty(value = "skipped")
    skipped("skipped"),

    @JsonProperty(value = "expired")
    expired("expired"),

    @JsonProperty(value = "canceled")
    canceled("canceled"),

    @JsonProperty(value = "pending_review")
    pendingReview("pending_review"),

    @JsonProperty(value = "manually_approved")
    manuallyApproved("manually_approved"),

    @JsonProperty(value = "manually_rejected")
    manuallyRejected("manually_rejected");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is IdentityVerificationStepStatus) "$data" else null

        /**
         * Returns a valid [IdentityVerificationStepStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): IdentityVerificationStepStatus? = data?.let {
            val normalizedData = "$it".lowercase()
            values().firstOrNull { value ->
                it == value || normalizedData == "$value".lowercase()
            }
        }
    }
}

