/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The identity data that was either collected from the user or provided via API in order to perform an identity verification.
 *
 * @param phoneNumber A phone number in E.164 format.
 * @param dateOfBirth A date in the format YYYY-MM-DD (RFC 3339 Section 5.6).
 * @param ipAddress An IPv4 or IPV6 address.
 * @param emailAddress
 * @param name
 * @param address
 * @param idNumber
 */

data class IdentityVerificationUserData(

    /* A phone number in E.164 format. */
    @field:JsonProperty("phone_number")
    val phoneNumber: kotlin.String?,

    /* A date in the format YYYY-MM-DD (RFC 3339 Section 5.6). */
    @field:JsonProperty("date_of_birth")
    val dateOfBirth: java.time.LocalDate?,

    /* An IPv4 or IPV6 address. */
    @field:JsonProperty("ip_address")
    val ipAddress: kotlin.String?,

    @field:JsonProperty("email_address")
    val emailAddress: kotlin.String?,

    @field:JsonProperty("name")
    val name: UserName?,

    @field:JsonProperty("address")
    val address: IdentityVerificationUserAddress?,

    @field:JsonProperty("id_number")
    val idNumber: UserIDNumber?

)

