/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The address of the employer
 *
 * @param city The full city name
 * @param country The ISO 3166-1 alpha-2 country code
 * @param postalCode The postal code. In API versions 2018-05-22 and earlier, this field is called `zip`.
 * @param region The region or state. In API versions 2018-05-22 and earlier, this field is called `state`. Example: `\"NC\"`
 * @param street The full street address Example: `\"564 Main Street, APT 15\"`
 */

data class IncomeVerificationPrecheckEmployerAddress(

    /* The full city name */
    @field:JsonProperty("city")
    val city: kotlin.String? = null,

    /* The ISO 3166-1 alpha-2 country code */
    @field:JsonProperty("country")
    val country: kotlin.String? = null,

    /* The postal code. In API versions 2018-05-22 and earlier, this field is called `zip`. */
    @field:JsonProperty("postal_code")
    val postalCode: kotlin.String? = null,

    /* The region or state. In API versions 2018-05-22 and earlier, this field is called `state`. Example: `\"NC\"` */
    @field:JsonProperty("region")
    val region: kotlin.String? = null,

    /* The full street address Example: `\"564 Main Street, APT 15\"` */
    @field:JsonProperty("street")
    val street: kotlin.String? = null

)

