/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The verified fields from a paystub verification. All fields are provided as reported on the paystub.
 *
 * @param employerName
 * @param employeeName
 * @param ytdGrossIncome
 * @param ytdNetIncome
 * @param payFrequency
 * @param projectedWage
 * @param verifiedTransaction
 */

data class IncomeSummary(

    @field:JsonProperty("employer_name")
    val employerName: EmployerIncomeSummaryFieldString,

    @field:JsonProperty("employee_name")
    val employeeName: EmployeeIncomeSummaryFieldString,

    @field:JsonProperty("ytd_gross_income")
    val ytdGrossIncome: YTDGrossIncomeSummaryFieldNumber,

    @field:JsonProperty("ytd_net_income")
    val ytdNetIncome: YTDNetIncomeSummaryFieldNumber,

    @field:JsonProperty("pay_frequency")
    val payFrequency: PayFrequency?,

    @field:JsonProperty("projected_wage")
    val projectedWage: ProjectedIncomeSummaryFieldNumber,

    @field:JsonProperty("verified_transaction")
    val verifiedTransaction: TransactionData?

) : kotlin.collections.HashMap<String, kotlin.Any>()

