/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Information about the user whose eligibility is being evaluated.
 *
 * @param firstName The user's first name
 * @param lastName The user's last name
 * @param emailAddress The user's email address
 * @param homeAddress
 */

data class IncomeVerificationPrecheckUser(

    /* The user's first name */
    @field:JsonProperty("first_name")
    val firstName: kotlin.String? = null,

    /* The user's last name */
    @field:JsonProperty("last_name")
    val lastName: kotlin.String? = null,

    /* The user's email address */
    @field:JsonProperty("email_address")
    val emailAddress: kotlin.String? = null,

    @field:JsonProperty("home_address")
    val homeAddress: SignalAddressData? = null

)

