/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * IncomeVerificationCreateRequest defines the request schema for `/income/verification/create`
 *
 * @param webhook The URL endpoint to which Plaid should send webhooks related to the progress of the income verification process.
 * @param clientId Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
 * @param secret Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
 * @param precheckId The ID of a precheck created with `/income/verification/precheck`. Will be used to improve conversion of the income verification flow.
 * @param options
 */

data class IncomeVerificationCreateRequest(

    /* The URL endpoint to which Plaid should send webhooks related to the progress of the income verification process. */
    @field:JsonProperty("webhook")
    val webhook: kotlin.String,

    /* Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
    @field:JsonProperty("client_id")
    val clientId: kotlin.String? = null,

    /* Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
    @field:JsonProperty("secret")
    val secret: kotlin.String? = null,

    /* The ID of a precheck created with `/income/verification/precheck`. Will be used to improve conversion of the income verification flow. */
    @field:JsonProperty("precheck_id")
    val precheckId: kotlin.String? = null,

    @field:JsonProperty("options")
    val options: IncomeVerificationCreateRequestOptions? = null

)

