/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Flow types to retrieve payroll income data
 *
 * Values: digitalIncome,documentIncome
 */

enum class IncomeVerificationPayrollFlowType(val value: kotlin.String) {

    @JsonProperty(value = "payroll_digital_income")
    digitalIncome("payroll_digital_income"),

    @JsonProperty(value = "payroll_document_income")
    documentIncome("payroll_document_income");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is IncomeVerificationPayrollFlowType) "$data" else null

        /**
         * Returns a valid [IncomeVerificationPayrollFlowType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): IncomeVerificationPayrollFlowType? = data?.let {
            val normalizedData = "$it".lowercase()
            values().firstOrNull { value ->
                it == value || normalizedData == "$value".lowercase()
            }
        }
    }
}

