/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Name information for the associated individual watchlist hit
 *
 * @param full The full name of the individual, including all parts.
 * @param isPrimary Primary names are those most commonly used to refer to this person. Only one name will ever be marked as primary.
 * @param weakAliasDetermination
 */

data class IndividualScreeningHitNames(

    /* The full name of the individual, including all parts. */
    @field:JsonProperty("full")
    val full: kotlin.String,

    /* Primary names are those most commonly used to refer to this person. Only one name will ever be marked as primary. */
    @field:JsonProperty("is_primary")
    val isPrimary: kotlin.Boolean,

    @field:JsonProperty("weak_alias_determination")
    val weakAliasDetermination: WeakAliasDetermination

)

