/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * An optional object to filter `/institutions/get` results.
 *
 * @param products Filter the Institutions based on which products they support.
 * @param routingNumbers Specify an array of routing numbers to filter institutions. The response will only return institutions that match all of the routing numbers in the array. Routing number records used for this matching are not comprehensive; failure to match a given routing number to an institution does not mean that the institution is unsupported by Plaid.
 * @param oauth Limit results to institutions with or without OAuth login flows.
 * @param includeOptionalMetadata When `true`, return the institution's homepage URL, logo and primary brand color.  Note that Plaid does not own any of the logos shared by the API, and that by accessing or using these logos, you agree that you are doing so at your own risk and will, if necessary, obtain all required permissions from the appropriate rights holders and adhere to any applicable usage guidelines. Plaid disclaims all express or implied warranties with respect to the logos.
 * @param includeAuthMetadata When `true`, returns metadata related to the Auth product indicating which auth methods are supported.
 * @param includePaymentInitiationMetadata When `true`, returns metadata related to the Payment Initiation product indicating which payment configurations are supported.
 */

data class InstitutionsGetRequestOptions(

    /* Filter the Institutions based on which products they support.  */
    @field:JsonProperty("products")
    val products: kotlin.collections.List<Products>? = null,

    /* Specify an array of routing numbers to filter institutions. The response will only return institutions that match all of the routing numbers in the array. Routing number records used for this matching are not comprehensive; failure to match a given routing number to an institution does not mean that the institution is unsupported by Plaid. */
    @field:JsonProperty("routing_numbers")
    val routingNumbers: kotlin.collections.List<kotlin.String>? = null,

    /* Limit results to institutions with or without OAuth login flows. */
    @field:JsonProperty("oauth")
    val oauth: kotlin.Boolean? = null,

    /* When `true`, return the institution's homepage URL, logo and primary brand color.  Note that Plaid does not own any of the logos shared by the API, and that by accessing or using these logos, you agree that you are doing so at your own risk and will, if necessary, obtain all required permissions from the appropriate rights holders and adhere to any applicable usage guidelines. Plaid disclaims all express or implied warranties with respect to the logos. */
    @field:JsonProperty("include_optional_metadata")
    val includeOptionalMetadata: kotlin.Boolean? = null,

    /* When `true`, returns metadata related to the Auth product indicating which auth methods are supported. */
    @field:JsonProperty("include_auth_metadata")
    val includeAuthMetadata: kotlin.Boolean? = false,

    /* When `true`, returns metadata related to the Payment Initiation product indicating which payment configurations are supported. */
    @field:JsonProperty("include_payment_initiation_metadata")
    val includePaymentInitiationMetadata: kotlin.Boolean? = false

)

