/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Information about the last successful and failed transactions update for the Item.
 *
 * @param investments
 * @param transactions
 * @param lastWebhook
 */

data class ItemStatusNullable(

    @field:JsonProperty("investments")
    val investments: ItemStatusInvestments? = null,

    @field:JsonProperty("transactions")
    val transactions: ItemStatusTransactions? = null,

    @field:JsonProperty("last_webhook")
    val lastWebhook: ItemStatusLastWebhook? = null

)

