/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Information specific to a mortgage loan agreement between one or more borrowers and a mortgage lender.
 *
 * @param loanRoleType An attribute of LOAN used to identify the role the associated LOAN plays in the transaction.
 * @param LOAN_IDENTIFIERS
 */

data class Loan(

    /* An attribute of LOAN used to identify the role the associated LOAN plays in the transaction. */
    @field:JsonProperty("LoanRoleType")
    val loanRoleType: kotlin.String,

    @field:JsonProperty("LOAN_IDENTIFIERS")
    val LOAN_IDENTIFIERS: LoanIdentifiers

) : kotlin.collections.HashMap<String, kotlin.Any>()

