/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The frequency of the pay period.
 *
 * @param `value`
 * @param verificationStatus
 */

data class PayFrequency(

    @field:JsonProperty("value")
    val `value`: PayFrequencyValue,

    @field:JsonProperty("verification_status")
    val verificationStatus: VerificationStatus

) : kotlin.collections.HashMap<String, kotlin.Any>()

