/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The status of the refund.  `PROCESSING`: The refund is currently being processed. The refund will automatically exit this state when processing is complete.  `INITIATED`: The refund has been successfully initiated.  `EXECUTED`: Indicates that the refund has been successfully executed.  `FAILED`: The refund has failed to be executed. This error is retryable once the root cause is resolved.
 *
 * Values: pROCESSING,eXECUTED,iNITIATED,fAILED
 */

enum class PaymentInitiationRefundStatus(val value: kotlin.String) {

    @JsonProperty(value = "PROCESSING")
    pROCESSING("PROCESSING"),

    @JsonProperty(value = "EXECUTED")
    eXECUTED("EXECUTED"),

    @JsonProperty(value = "INITIATED")
    iNITIATED("INITIATED"),

    @JsonProperty(value = "FAILED")
    fAILED("FAILED");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PaymentInitiationRefundStatus) "$data" else null

        /**
         * Returns a valid [PaymentInitiationRefundStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PaymentInitiationRefundStatus? = data?.let {
            val normalizedData = "$it".lowercase()
            values().firstOrNull { value ->
                it == value || normalizedData == "$value".lowercase()
            }
        }
    }
}

