/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Details about the pay period.
 *
 * @param checkAmount The amount of the paycheck.
 * @param distributionBreakdown
 * @param endDate The pay period end date, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format: \"yyyy-mm-dd\".
 * @param grossEarnings Total earnings before tax/deductions.
 * @param payDate The date on which the paystub was issued, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (\"yyyy-mm-dd\").
 * @param payFrequency The frequency at which an individual is paid.
 * @param payDay The date on which the paystub was issued, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (\"yyyy-mm-dd\").
 * @param startDate The pay period start date, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format: \"yyyy-mm-dd\".
 */

data class PayPeriodDetails(

    /* The amount of the paycheck. */
    @field:JsonProperty("check_amount")
    val checkAmount: kotlin.Double? = null,

    @field:JsonProperty("distribution_breakdown")
    val distributionBreakdown: kotlin.collections.List<DistributionBreakdown>? = null,

    /* The pay period end date, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format: \"yyyy-mm-dd\". */
    @field:JsonProperty("end_date")
    val endDate: java.time.LocalDate? = null,

    /* Total earnings before tax/deductions. */
    @field:JsonProperty("gross_earnings")
    val grossEarnings: kotlin.Double? = null,

    /* The date on which the paystub was issued, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (\"yyyy-mm-dd\"). */
    @field:JsonProperty("pay_date")
    val payDate: java.time.LocalDate? = null,

    /* The frequency at which an individual is paid. */
    @field:JsonProperty("pay_frequency")
    val payFrequency: PayFrequency? = null,

    /* The date on which the paystub was issued, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (\"yyyy-mm-dd\"). */
    @field:JsonProperty("pay_day")
    @Deprecated(message = "This property is deprecated.")
    val payDay: java.time.LocalDate? = null,

    /* The pay period start date, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format: \"yyyy-mm-dd\". */
    @field:JsonProperty("start_date")
    val startDate: java.time.LocalDate? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {

    /**
     * The frequency at which an individual is paid.
     *
     * Values: uNKNOWN,wEEKLY,bIWEEKLY,sEMIMONTHLY,mONTHLY
     */
    enum class PayFrequency(val value: kotlin.String) {
        @JsonProperty(value = "PAY_FREQUENCY_UNKNOWN")
        uNKNOWN("PAY_FREQUENCY_UNKNOWN"),
        @JsonProperty(value = "PAY_FREQUENCY_WEEKLY")
        wEEKLY("PAY_FREQUENCY_WEEKLY"),
        @JsonProperty(value = "PAY_FREQUENCY_BIWEEKLY")
        bIWEEKLY("PAY_FREQUENCY_BIWEEKLY"),
        @JsonProperty(value = "PAY_FREQUENCY_SEMIMONTHLY")
        sEMIMONTHLY("PAY_FREQUENCY_SEMIMONTHLY"),
        @JsonProperty(value = "PAY_FREQUENCY_MONTHLY")
        mONTHLY("PAY_FREQUENCY_MONTHLY");
    }
}

