/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * An object representing details that can be found on the paystub.
 *
 * @param payPeriodStartDate Beginning date of the pay period on the paystub in the 'YYYY-MM-DD' format.
 * @param payPeriodEndDate Ending date of the pay period on the paystub in the 'YYYY-MM-DD' format.
 * @param payDate Pay date on the paystub in the 'YYYY-MM-DD' format.
 * @param paystubProvider The name of the payroll provider that generated the paystub, e.g. ADP
 * @param payFrequency
 */

@Deprecated(message = "This schema is deprecated.")
data class PaystubDetails(

    /* Beginning date of the pay period on the paystub in the 'YYYY-MM-DD' format. */
    @field:JsonProperty("pay_period_start_date")
    val payPeriodStartDate: java.time.LocalDate? = null,

    /* Ending date of the pay period on the paystub in the 'YYYY-MM-DD' format. */
    @field:JsonProperty("pay_period_end_date")
    val payPeriodEndDate: java.time.LocalDate? = null,

    /* Pay date on the paystub in the 'YYYY-MM-DD' format. */
    @field:JsonProperty("pay_date")
    val payDate: java.time.LocalDate? = null,

    /* The name of the payroll provider that generated the paystub, e.g. ADP */
    @field:JsonProperty("paystub_provider")
    val paystubProvider: kotlin.String? = null,

    @field:JsonProperty("pay_frequency")
    val payFrequency: PaystubPayFrequency? = null

) : kotlin.collections.HashMap<String, kotlin.Any>()

