/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * An object representing the earnings line items for the pay period.
 *
 * @param canonicalDescription Commonly used term to describe the earning line item.
 * @param currentAmount Raw amount of the earning line item.
 * @param description Description of the earning line item.
 * @param hours Number of hours applicable for this earning.
 * @param isoCurrencyCode The ISO-4217 currency code of the line item. Always `null` if `unofficial_currency_code` is non-null.
 * @param rate Hourly rate applicable for this earning.
 * @param unofficialCurrencyCode The unofficial currency code associated with the line item. Always `null` if `iso_currency_code` is non-`null`. Unofficial currency codes are used for currencies that do not have official ISO currency codes, such as cryptocurrencies and the currencies of certain countries.  See the [currency code schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a full listing of supported `iso_currency_code`s.
 * @param ytdAmount The year-to-date amount of the deduction.
 */

data class PayStubEarningsBreakdown(

    /* Commonly used term to describe the earning line item. */
    @field:JsonProperty("canonical_description")
    val canonicalDescription: kotlin.String?,

    /* Raw amount of the earning line item. */
    @field:JsonProperty("current_amount")
    val currentAmount: kotlin.Double?,

    /* Description of the earning line item. */
    @field:JsonProperty("description")
    val description: kotlin.String?,

    /* Number of hours applicable for this earning. */
    @field:JsonProperty("hours")
    val hours: java.math.BigDecimal?,

    /* The ISO-4217 currency code of the line item. Always `null` if `unofficial_currency_code` is non-null. */
    @field:JsonProperty("iso_currency_code")
    val isoCurrencyCode: kotlin.String?,

    /* Hourly rate applicable for this earning. */
    @field:JsonProperty("rate")
    val rate: kotlin.Double?,

    /* The unofficial currency code associated with the line item. Always `null` if `iso_currency_code` is non-`null`. Unofficial currency codes are used for currencies that do not have official ISO currency codes, such as cryptocurrencies and the currencies of certain countries.  See the [currency code schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a full listing of supported `iso_currency_code`s. */
    @field:JsonProperty("unofficial_currency_code")
    val unofficialCurrencyCode: kotlin.String?,

    /* The year-to-date amount of the deduction. */
    @field:JsonProperty("ytd_amount")
    val ytdAmount: kotlin.Double?

) : kotlin.collections.HashMap<String, kotlin.Any>()

