/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The request was flagged by Plaid's fraud system, and requires additional verification to ensure they are not a bot.
 *
 * @param errorType RECAPTCHA_ERROR
 * @param errorCode RECAPTCHA_REQUIRED
 * @param displayMessage
 * @param httpCode 400
 * @param linkUserExperience Your user will be prompted to solve a Google reCAPTCHA challenge in the Link Recaptcha pane. If they solve the challenge successfully, the user's request is resubmitted and they are directed to the next Item creation step.
 * @param commonCauses Plaid's fraud system detects abusive traffic and considers a variety of parameters throughout Item creation requests. When a request is considered risky or possibly fraudulent, Link presents a reCAPTCHA for the user to solve.
 * @param troubleshootingSteps Link will automatically guide your user through reCAPTCHA verification. As a general rule, we recommend instrumenting basic fraud monitoring to detect and protect your website from spam and abuse.  If your user cannot verify their session, please submit a Support ticket with the following identifiers: `link_session_id` or `request_id`
 */

data class RecaptchaRequiredError(

    /* RECAPTCHA_ERROR */
    @field:JsonProperty("error_type")
    val errorType: kotlin.String,

    /* RECAPTCHA_REQUIRED */
    @field:JsonProperty("error_code")
    val errorCode: kotlin.String,

    @field:JsonProperty("display_message")
    val displayMessage: kotlin.String,

    /* 400 */
    @field:JsonProperty("http_code")
    val httpCode: kotlin.String,

    /* Your user will be prompted to solve a Google reCAPTCHA challenge in the Link Recaptcha pane. If they solve the challenge successfully, the user's request is resubmitted and they are directed to the next Item creation step. */
    @field:JsonProperty("link_user_experience")
    val linkUserExperience: kotlin.String,

    /* Plaid's fraud system detects abusive traffic and considers a variety of parameters throughout Item creation requests. When a request is considered risky or possibly fraudulent, Link presents a reCAPTCHA for the user to solve. */
    @field:JsonProperty("common_causes")
    val commonCauses: kotlin.String,

    /* Link will automatically guide your user through reCAPTCHA verification. As a general rule, we recommend instrumenting basic fraud monitoring to detect and protect your website from spam and abuse.  If your user cannot verify their session, please submit a Support ticket with the following identifiers: `link_session_id` or `request_id` */
    @field:JsonProperty("troubleshooting_steps")
    val troubleshootingSteps: kotlin.String

) : kotlin.collections.HashMap<String, kotlin.Any>()

