/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Fired when an Item's recurring transactions data is updated. After receipt of this webhook, the updated data can be fetched from `/transactions/recurring/get`.
 *
 * @param webhookType `TRANSACTIONS`
 * @param webhookCode `RECURRING_TRANSACTIONS_UPDATE`
 * @param itemId The `item_id` of the Item associated with this webhook, warning, or error
 * @param accountIds A list of `account_ids` for accounts that have new or updated recurring transactions data.
 */

data class RecurringTransactionsUpdateWebhook(

    /* `TRANSACTIONS` */
    @field:JsonProperty("webhook_type")
    val webhookType: kotlin.String,

    /* `RECURRING_TRANSACTIONS_UPDATE` */
    @field:JsonProperty("webhook_code")
    val webhookCode: kotlin.String,

    /* The `item_id` of the Item associated with this webhook, warning, or error */
    @field:JsonProperty("item_id")
    val itemId: kotlin.String,

    /* A list of `account_ids` for accounts that have new or updated recurring transactions data. */
    @field:JsonProperty("account_ids")
    val accountIds: kotlin.collections.List<kotlin.String>

) : kotlin.collections.HashMap<String, kotlin.Any>()

