/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * An optional object to be used with the request. If specified, `options` must not be `null`.
 *
 * @param accountIds A list of `account_ids` to retrieve for the Item  Note: An error will be returned if a provided `account_id` is not associated with the Item.
 * @param count The number of transactions to fetch.
 * @param offset The number of transactions to skip. The default value is 0.
 * @param includeOriginalDescription Include the raw unparsed transaction description from the financial institution. This field is disabled by default. If you need this information in addition to the parsed data provided, contact your Plaid Account Manager.
 * @param includePersonalFinanceCategoryBeta Please use [`include_personal_finance_category`](https://plaid.com/docs/api/products/transactions/#transactions-get-request-options-include-personal-finance-category) instead.
 * @param includePersonalFinanceCategory Include the [`personal_finance_category`](https://plaid.com/docs/api/products/transactions/#transactions-get-response-transactions-personal-finance-category) object in the response.  See the [`taxonomy csv file`](https://plaid.com/documents/transactions-personal-finance-category-taxonomy.csv) for a full list of personal finance categories.  We’re introducing Category Rules - a new beta endpoint that will enable you to change the `personal_finance_category` for a transaction based on your users’ needs. When rules are set, the selected category will override the Plaid provided category. To learn more, send a note to transactions-feedback@plaid.com.
 */

data class TransactionsGetRequestOptions(

    /* A list of `account_ids` to retrieve for the Item  Note: An error will be returned if a provided `account_id` is not associated with the Item. */
    @field:JsonProperty("account_ids")
    val accountIds: kotlin.collections.List<kotlin.String>? = null,

    /* The number of transactions to fetch. */
    @field:JsonProperty("count")
    val count: kotlin.Int? = 100,

    /* The number of transactions to skip. The default value is 0. */
    @field:JsonProperty("offset")
    val offset: kotlin.Int? = 0,

    /* Include the raw unparsed transaction description from the financial institution. This field is disabled by default. If you need this information in addition to the parsed data provided, contact your Plaid Account Manager. */
    @field:JsonProperty("include_original_description")
    val includeOriginalDescription: kotlin.Boolean? = false,

    /* Please use [`include_personal_finance_category`](https://plaid.com/docs/api/products/transactions/#transactions-get-request-options-include-personal-finance-category) instead. */
    @field:JsonProperty("include_personal_finance_category_beta")
    @Deprecated(message = "This property is deprecated.")
    val includePersonalFinanceCategoryBeta: kotlin.Boolean? = false,

    /**
     * Include the [`personal_finance_category`](https://plaid.com/docs/api/products/transactions/#transactions-get-response-transactions-personal-finance-category) object in the response.  See the [`taxonomy csv file`](https://plaid.com/documents/transactions-personal-finance-category-taxonomy.csv) for a full list of personal finance categories.  We’re introducing Category Rules - a new beta endpoint that will enable you to change the `personal_finance_category` for a transaction based on your users’ needs. When rules are set, the selected category will override the Plaid provided category. To learn more, send a note to transactions-feedback@plaid.com.
     *
     * This can be set to false, but do not do so as this particular API client is configured to always expect it.
     */
    @field:JsonProperty("include_personal_finance_category")
    val includePersonalFinanceCategory: kotlin.Boolean? = true

)

