/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Information about the matched direct deposit transaction used to verify a user's payroll information.
 *
 * @param description The description of the transaction.
 * @param amount The amount of the transaction.
 * @param date The date of the transaction, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (\"yyyy-mm-dd\").
 * @param accountId A unique identifier for the end user's account.
 * @param transactionId A unique identifier for the transaction.
 */

data class TransactionData(

    /* The description of the transaction. */
    @field:JsonProperty("description")
    val description: kotlin.String,

    /* The amount of the transaction. */
    @field:JsonProperty("amount")
    val amount: kotlin.Double,

    /* The date of the transaction, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (\"yyyy-mm-dd\"). */
    @field:JsonProperty("date")
    val date: java.time.LocalDate,

    /* A unique identifier for the end user's account. */
    @field:JsonProperty("account_id")
    val accountId: kotlin.String,

    /* A unique identifier for the transaction. */
    @field:JsonProperty("transaction_id")
    val transactionId: kotlin.String

) : kotlin.collections.HashMap<String, kotlin.Any>()

