/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.plaid.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Search terms for creating an individual watchlist screening
 *
 * @param watchlistProgramId ID of the associated program.
 * @param legalName The legal name of the individual being screened.
 * @param dateOfBirth
 * @param documentNumber
 * @param country
 * @param version The current version of the search terms. Starts at `1` and increments with each edit to `search_terms`.
 */

data class WatchlistScreeningSearchTerms(

    /* ID of the associated program. */
    @field:JsonProperty("watchlist_program_id")
    val watchlistProgramId: kotlin.String,

    /* The legal name of the individual being screened. */
    @field:JsonProperty("legal_name")
    val legalName: kotlin.String,

    @field:JsonProperty("date_of_birth")
    val dateOfBirth: java.time.LocalDate?,

    @field:JsonProperty("document_number")
    val documentNumber: kotlin.String?,

    @field:JsonProperty("country")
    val country: kotlin.String?,

    /* The current version of the search terms. Starts at `1` and increments with each edit to `search_terms`. */
    @field:JsonProperty("version")
    val version: java.math.BigDecimal

)

