/**
 * Firefly III API v1.5.6
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.firefly.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param id
 * @param name Name of the piggy bank found by an auto-complete search.
 * @param currencyId Currency ID for this piggy bank.
 * @param currencyCode Currency code for this piggy bank.
 * @param currencySymbol
 * @param currencyName Currency name for the currency used by this account.
 * @param currencyDecimalPlaces
 * @param objectGroupId The group ID of the group this object is part of. NULL if no group.
 * @param objectGroupTitle The name of the group. NULL if no group.
 */

data class AutocompletePiggy(

    @field:JsonProperty("id")
    val id: kotlin.String,

    /* Name of the piggy bank found by an auto-complete search. */
    @field:JsonProperty("name")
    val name: kotlin.String,

    /* Currency ID for this piggy bank. */
    @field:JsonProperty("currency_id")
    val currencyId: kotlin.String? = null,

    /* Currency code for this piggy bank. */
    @field:JsonProperty("currency_code")
    val currencyCode: kotlin.String? = null,

    @field:JsonProperty("currency_symbol")
    val currencySymbol: kotlin.String? = null,

    /* Currency name for the currency used by this account. */
    @field:JsonProperty("currency_name")
    val currencyName: kotlin.String? = null,

    @field:JsonProperty("currency_decimal_places")
    val currencyDecimalPlaces: kotlin.Int? = null,

    /* The group ID of the group this object is part of. NULL if no group. */
    @field:JsonProperty("object_group_id")
    val objectGroupId: kotlin.String? = null,

    /* The name of the group. NULL if no group. */
    @field:JsonProperty("object_group_title")
    val objectGroupTitle: kotlin.String? = null

)

