/**
 * Firefly III API v1.5.6
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.firefly.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param code
 * @param name
 * @param symbol
 * @param createdAt
 * @param updatedAt
 * @param enabled Defaults to true
 * @param default Make this currency the default currency.
 * @param decimalPlaces Supports 0-16 decimals.
 */

data class Currency(

    @field:JsonProperty("code")
    val code: kotlin.String,

    @field:JsonProperty("name")
    val name: kotlin.String,

    @field:JsonProperty("symbol")
    val symbol: kotlin.String,

    @field:JsonProperty("created_at")
    val createdAt: java.time.OffsetDateTime? = null,

    @field:JsonProperty("updated_at")
    val updatedAt: java.time.OffsetDateTime? = null,

    /* Defaults to true */
    @field:JsonProperty("enabled")
    val enabled: kotlin.Boolean? = true,

    /* Make this currency the default currency. */
    @field:JsonProperty("default")
    val default: kotlin.Boolean? = null,

    /* Supports 0-16 decimals. */
    @field:JsonProperty("decimal_places")
    val decimalPlaces: kotlin.Int? = null

)

