/**
 * Firefly III API v1.5.6
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually. I DO WHAT I WANT
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.api.firefly.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param self
 * @param first
 * @param last
 */

data class PageLink(
    @field:JsonProperty("prev")
    val prev: java.net.URI? = null,

    @field:JsonProperty("next")
    val next: java.net.URI? = null,

    @field:JsonProperty("self")
    val self: java.net.URI? = null,

    @field:JsonProperty("first")
    val first: java.net.URI? = null,

    @field:JsonProperty("last")
    val last: java.net.URI? = null

)

