/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Allow or disallow product access by account. Unlisted (e.g. missing) accounts will be considered `new_accounts`.
 *
 * @param uniqueId The unique account identifier for this account. This value must match that returned by the data access API for this account.
 * @param authorized Allow the application to see this account (and associated details, including balance) in the list of accounts  If unset, defaults to `true`.
 * @param accountProductAccess
 */

data class AccountAccess(

    /* The unique account identifier for this account. This value must match that returned by the data access API for this account. */
    @field:JsonProperty("unique_id")
    val uniqueId: kotlin.String,

    /* Allow the application to see this account (and associated details, including balance) in the list of accounts  If unset, defaults to `true`. */
    @field:JsonProperty("authorized")
    val authorized: kotlin.Boolean? = true,

    @field:JsonProperty("account_product_access")
    val accountProductAccess: AccountProductAccessNullable? = null

)

