/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The object containing employment items.
 *
 * @param itemId The `item_id` of the Item associated with this webhook, warning, or error
 * @param employments
 * @param employmentReportToken Token to represent the underlying Employment data
 */

data class CreditEmploymentItem(

    /* The `item_id` of the Item associated with this webhook, warning, or error */
    @field:JsonProperty("item_id")
    val itemId: kotlin.String,

    @field:JsonProperty("employments")
    val employments: kotlin.collections.List<CreditEmploymentVerification>,

    /* Token to represent the underlying Employment data */
    @field:JsonProperty("employment_report_token")
    val employmentReportToken: kotlin.String

) : kotlin.collections.HashMap<String, kotlin.Any>()

