/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The warning associated with the data that was unavailable for the Bank Income Report.
 *
 * @param warningType
 * @param warningCode
 * @param cause
 */

data class CreditBankIncomeWarning(

    @field:JsonProperty("warning_type")
    val warningType: CreditBankIncomeWarningType? = null,

    @field:JsonProperty("warning_code")
    val warningCode: CreditBankIncomeWarningCode? = null,

    @field:JsonProperty("cause")
    val cause: CreditBankIncomeCause? = null

)

