/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * DepositSwitchCreateRequest defines the request schema for `/deposit_switch/create`
 *
 * @param targetAccessToken Access token for the target Item, typically provided in the Import Item response.
 * @param targetAccountId Plaid Account ID that specifies the target bank account. This account will become the recipient for a user's direct deposit.
 * @param clientId Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
 * @param secret Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
 * @param countryCode ISO-3166-1 alpha-2 country code standard.
 * @param options
 */

data class DepositSwitchCreateRequest(

    /* Access token for the target Item, typically provided in the Import Item response.  */
    @field:JsonProperty("target_access_token")
    val targetAccessToken: kotlin.String,

    /* Plaid Account ID that specifies the target bank account. This account will become the recipient for a user's direct deposit. */
    @field:JsonProperty("target_account_id")
    val targetAccountId: kotlin.String,

    /* Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
    @field:JsonProperty("client_id")
    val clientId: kotlin.String? = null,

    /* Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
    @field:JsonProperty("secret")
    val secret: kotlin.String? = null,

    /* ISO-3166-1 alpha-2 country code standard. */
    @field:JsonProperty("country_code")
    val countryCode: DepositSwitchCreateRequest.CountryCode? = null,

    @field:JsonProperty("options")
    val options: DepositSwitchCreateRequestOptions? = null

) {

    /**
     * ISO-3166-1 alpha-2 country code standard.
     *
     * Values: uS,cA
     */
    enum class CountryCode(val value: kotlin.String) {
        @JsonProperty(value = "US")
        uS("US"),
        @JsonProperty(value = "CA")
        cA("CA");
    }
}

