/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Details about a certain reason as to why a document could potentially be fraudulent.
 *
 * @param type The result from the risk signal check.
 * @param `field` The field which the risk signal was computed for
 * @param hasFraudRisk A flag used to quickly identify if the signal indicates that this field is authentic or fraudulent
 * @param institutionMetadata
 * @param expectedValue The expected value of the field, as seen on the document
 * @param actualValue The derived value obtained in the risk signal calculation process for this field
 * @param signalDescription A human-readable explanation providing more detail into the particular risk signal
 */

data class DocumentRiskSignal(

    /* The result from the risk signal check. */
    @field:JsonProperty("type")
    val type: kotlin.String?,

    /* The field which the risk signal was computed for */
    @field:JsonProperty("field")
    val `field`: kotlin.String?,

    /* A flag used to quickly identify if the signal indicates that this field is authentic or fraudulent */
    @field:JsonProperty("has_fraud_risk")
    val hasFraudRisk: kotlin.Boolean?,

    @field:JsonProperty("institution_metadata")
    val institutionMetadata: DocumentRiskSignalInstitutionMetadata?,

    /* The expected value of the field, as seen on the document */
    @field:JsonProperty("expected_value")
    val expectedValue: kotlin.String?,

    /* The derived value obtained in the risk signal calculation process for this field */
    @field:JsonProperty("actual_value")
    val actualValue: kotlin.String?,

    /* A human-readable explanation providing more detail into the particular risk signal */
    @field:JsonProperty("signal_description")
    val signalDescription: kotlin.String?

) : kotlin.collections.HashMap<String, kotlin.Any>()

