/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Search terms associated with an entity used for searching against watchlists
 *
 * @param entityWatchlistProgramId ID of the associated entity program.
 * @param legalName The name of the organization being screened.
 * @param documentNumber
 * @param emailAddress
 * @param country
 * @param phoneNumber
 * @param url
 * @param version The current version of the search terms. Starts at `1` and increments with each edit to `search_terms`.
 */

data class EntityWatchlistScreeningSearchTerms(

    /* ID of the associated entity program. */
    @field:JsonProperty("entity_watchlist_program_id")
    val entityWatchlistProgramId: kotlin.String,

    /* The name of the organization being screened. */
    @field:JsonProperty("legal_name")
    val legalName: kotlin.String,

    @field:JsonProperty("document_number")
    val documentNumber: kotlin.String?,

    @field:JsonProperty("email_address")
    val emailAddress: kotlin.String?,

    @field:JsonProperty("country")
    val country: kotlin.String?,

    @field:JsonProperty("phone_number")
    val phoneNumber: kotlin.String?,

    @field:JsonProperty("url")
    val url: java.net.URI?,

    /* The current version of the search terms. Starts at `1` and increments with each edit to `search_terms`. */
    @field:JsonProperty("version")
    val version: java.math.BigDecimal

)

