/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * An update on the health incident
 *
 * @param description The content of the update.
 * @param status The status of the incident.
 * @param updatedDate The date when the update was published, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format, e.g. `\"2020-10-30T15:26:48Z\"`.
 */

data class IncidentUpdate(

    /* The content of the update. */
    @field:JsonProperty("description")
    val description: kotlin.String? = null,

    /* The status of the incident. */
    @field:JsonProperty("status")
    val status: IncidentUpdate.Status? = null,

    /* The date when the update was published, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format, e.g. `\"2020-10-30T15:26:48Z\"`. */
    @field:JsonProperty("updated_date")
    val updatedDate: java.time.OffsetDateTime? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {

    /**
     * The status of the incident.
     *
     * Values: iNVESTIGATING,iDENTIFIED,sCHEDULED,rESOLVED,uNKNOWN
     */
    enum class Status(val value: kotlin.String) {
        @JsonProperty(value = "INVESTIGATING")
        iNVESTIGATING("INVESTIGATING"),
        @JsonProperty(value = "IDENTIFIED")
        iDENTIFIED("IDENTIFIED"),
        @JsonProperty(value = "SCHEDULED")
        sCHEDULED("SCHEDULED"),
        @JsonProperty(value = "RESOLVED")
        rESOLVED("RESOLVED"),
        @JsonProperty(value = "UNKNOWN")
        uNKNOWN("UNKNOWN");
    }
}

