/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Specify payroll data on the account.
 *
 * @param paystubs A list of paystubs associated with the account.
 */

data class IncomeOverride(

    /* A list of paystubs associated with the account. */
    @field:JsonProperty("paystubs")
    val paystubs: kotlin.collections.List<PaystubOverride>? = null

)

