/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * An optional object to filter `/institutions/search` results.
 *
 * @param oauth Limit results to institutions with or without OAuth login flows.
 * @param includeOptionalMetadata When true, return the institution's homepage URL, logo and primary brand color.
 * @param includeAuthMetadata When `true`, returns metadata related to the Auth product indicating which auth methods are supported.
 * @param includePaymentInitiationMetadata When `true`, returns metadata related to the Payment Initiation product indicating which payment configurations are supported.
 * @param paymentInitiation
 */

data class InstitutionsSearchRequestOptions(

    /* Limit results to institutions with or without OAuth login flows. */
    @field:JsonProperty("oauth")
    val oauth: kotlin.Boolean? = null,

    /* When true, return the institution's homepage URL, logo and primary brand color. */
    @field:JsonProperty("include_optional_metadata")
    val includeOptionalMetadata: kotlin.Boolean? = null,

    /* When `true`, returns metadata related to the Auth product indicating which auth methods are supported. */
    @field:JsonProperty("include_auth_metadata")
    val includeAuthMetadata: kotlin.Boolean? = false,

    /* When `true`, returns metadata related to the Payment Initiation product indicating which payment configurations are supported. */
    @field:JsonProperty("include_payment_initiation_metadata")
    val includePaymentInitiationMetadata: kotlin.Boolean? = false,

    @field:JsonProperty("payment_initiation")
    val paymentInitiation: InstitutionsSearchPaymentInitiationOptions? = null

)

