/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The user's full name. Optional if using the [Identity Verification](https://plaid.com/docs/api/products/identity-verification) product; if not using Identity Verification, this field is not allowed. Users will not be asked for their name when this field is provided.
 *
 * @param givenName A string with at least one non-whitespace character, with a max length of 100 characters.
 * @param familyName A string with at least one non-whitespace character, with a max length of 100 characters.
 */

data class LinkTokenCreateRequestUserName(

    /* A string with at least one non-whitespace character, with a max length of 100 characters. */
    @field:JsonProperty("given_name")
    val givenName: kotlin.String,

    /* A string with at least one non-whitespace character, with a max length of 100 characters. */
    @field:JsonProperty("family_name")
    val familyName: kotlin.String

)

