/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Allows specifying the metadata of the test account
 *
 * @param name The account's name
 * @param officialName The account's official name
 * @param limit The account's limit
 */

data class Meta(

    /* The account's name */
    @field:JsonProperty("name")
    val name: kotlin.String,

    /* The account's official name */
    @field:JsonProperty("official_name")
    val officialName: kotlin.String,

    /* The account's limit */
    @field:JsonProperty("limit")
    val limit: kotlin.Double

) : kotlin.collections.HashMap<String, kotlin.Any>()

