/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Contains details about a mortgage account.
 *
 * @param accountId The ID of the account that this liability belongs to.
 * @param accountNumber The account number of the loan.
 * @param currentLateFee The current outstanding amount charged for late payment.
 * @param escrowBalance Total amount held in escrow to pay taxes and insurance on behalf of the borrower.
 * @param hasPmi Indicates whether the borrower has private mortgage insurance in effect.
 * @param hasPrepaymentPenalty Indicates whether the borrower will pay a penalty for early payoff of mortgage.
 * @param interestRate
 * @param lastPaymentAmount The amount of the last payment.
 * @param lastPaymentDate The date of the last payment. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
 * @param loanTypeDescription Description of the type of loan, for example `conventional`, `fixed`, or `variable`. This field is provided directly from the loan servicer and does not have an enumerated set of possible values.
 * @param loanTerm Full duration of mortgage as at origination (e.g. `10 year`).
 * @param maturityDate Original date on which mortgage is due in full. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
 * @param nextMonthlyPayment The amount of the next payment.
 * @param nextPaymentDueDate The due date for the next payment. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
 * @param originationDate The date on which the loan was initially lent. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
 * @param originationPrincipalAmount The original principal balance of the mortgage.
 * @param pastDueAmount Amount of loan (principal + interest) past due for payment.
 * @param propertyAddress
 * @param ytdInterestPaid The year to date (YTD) interest paid.
 * @param ytdPrincipalPaid The YTD principal paid.
 */

data class MortgageLiability(

    /* The ID of the account that this liability belongs to. */
    @field:JsonProperty("account_id")
    val accountId: kotlin.String,

    /* The account number of the loan. */
    @field:JsonProperty("account_number")
    val accountNumber: kotlin.String,

    /* The current outstanding amount charged for late payment. */
    @field:JsonProperty("current_late_fee")
    val currentLateFee: kotlin.Double?,

    /* Total amount held in escrow to pay taxes and insurance on behalf of the borrower. */
    @field:JsonProperty("escrow_balance")
    val escrowBalance: kotlin.Double?,

    /* Indicates whether the borrower has private mortgage insurance in effect. */
    @field:JsonProperty("has_pmi")
    val hasPmi: kotlin.Boolean?,

    /* Indicates whether the borrower will pay a penalty for early payoff of mortgage. */
    @field:JsonProperty("has_prepayment_penalty")
    val hasPrepaymentPenalty: kotlin.Boolean?,

    @field:JsonProperty("interest_rate")
    val interestRate: MortgageInterestRate,

    /* The amount of the last payment. */
    @field:JsonProperty("last_payment_amount")
    val lastPaymentAmount: kotlin.Double?,

    /* The date of the last payment. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD). */
    @field:JsonProperty("last_payment_date")
    val lastPaymentDate: java.time.LocalDate?,

    /* Description of the type of loan, for example `conventional`, `fixed`, or `variable`. This field is provided directly from the loan servicer and does not have an enumerated set of possible values. */
    @field:JsonProperty("loan_type_description")
    val loanTypeDescription: kotlin.String?,

    /* Full duration of mortgage as at origination (e.g. `10 year`). */
    @field:JsonProperty("loan_term")
    val loanTerm: kotlin.String?,

    /* Original date on which mortgage is due in full. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD). */
    @field:JsonProperty("maturity_date")
    val maturityDate: java.time.LocalDate?,

    /* The amount of the next payment. */
    @field:JsonProperty("next_monthly_payment")
    val nextMonthlyPayment: kotlin.Double?,

    /* The due date for the next payment. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD). */
    @field:JsonProperty("next_payment_due_date")
    val nextPaymentDueDate: java.time.LocalDate?,

    /* The date on which the loan was initially lent. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD). */
    @field:JsonProperty("origination_date")
    val originationDate: java.time.LocalDate?,

    /* The original principal balance of the mortgage. */
    @field:JsonProperty("origination_principal_amount")
    val originationPrincipalAmount: kotlin.Double?,

    /* Amount of loan (principal + interest) past due for payment. */
    @field:JsonProperty("past_due_amount")
    val pastDueAmount: kotlin.Double?,

    @field:JsonProperty("property_address")
    val propertyAddress: MortgagePropertyAddress,

    /* The year to date (YTD) interest paid. */
    @field:JsonProperty("ytd_interest_paid")
    val ytdInterestPaid: kotlin.Double?,

    /* The YTD principal paid. */
    @field:JsonProperty("ytd_principal_paid")
    val ytdPrincipalPaid: kotlin.Double?

) : kotlin.collections.HashMap<String, kotlin.Any>()

