/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Identifying information for transferring money to or from a Canadian bank account via EFT.
 *
 * @param accountId The Plaid account ID associated with the account numbers
 * @param account The EFT account number for the account
 * @param institution The EFT institution number for the account
 * @param branch The EFT branch number for the account
 */

data class NumbersEFT(

    /* The Plaid account ID associated with the account numbers */
    @field:JsonProperty("account_id")
    val accountId: kotlin.String,

    /* The EFT account number for the account */
    @field:JsonProperty("account")
    val account: kotlin.String,

    /* The EFT institution number for the account */
    @field:JsonProperty("institution")
    val institution: kotlin.String,

    /* The EFT branch number for the account */
    @field:JsonProperty("branch")
    val branch: kotlin.String

) : kotlin.collections.HashMap<String, kotlin.Any>()

