/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Object containing fraud risk data pertaining to the item linked as part of the verification
 *
 * @param itemId The `item_id` of the Item associated with this webhook, warning, or error
 * @param verificationRiskSignals Array of payroll income document authenticity data retrieved for each of the user's accounts
 */

data class PayrollRiskSignalsItem(

    /* The `item_id` of the Item associated with this webhook, warning, or error */
    @field:JsonProperty("item_id")
    val itemId: kotlin.String,

    /* Array of payroll income document authenticity data retrieved for each of the user's accounts */
    @field:JsonProperty("verification_risk_signals")
    val verificationRiskSignals: kotlin.collections.List<DocumentRiskSignalsObject>

) : kotlin.collections.HashMap<String, kotlin.Any>()

