/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * An object representing payroll data.
 *
 * @param accountId ID of the payroll provider account.
 * @param payStubs Array of pay stubs for the user.
 * @param w2s Array of tax form W-2s.
 * @param form1099s Array of tax form 1099s.
 */

data class PayrollIncomeObject(

    /* ID of the payroll provider account. */
    @field:JsonProperty("account_id")
    val accountId: kotlin.String?,

    /* Array of pay stubs for the user. */
    @field:JsonProperty("pay_stubs")
    val payStubs: kotlin.collections.List<CreditPayStub>,

    /* Array of tax form W-2s. */
    @field:JsonProperty("w2s")
    val w2s: kotlin.collections.List<CreditW2>,

    /* Array of tax form 1099s. */
    @field:JsonProperty("form1099s")
    val form1099s: kotlin.collections.List<Credit1099>

) : kotlin.collections.HashMap<String, kotlin.Any>()

