/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * An object containing identifying numbers used for making electronic transfers to and from the `account`. The identifying number type (ACH, EFT, IBAN, or BACS) used will depend on the country of the account. An account may have more than one number type. If a particular identifying number type is not used by the `account` for which auth data has been requested, a null value will be returned.
 *
 * @param ach
 * @param eft
 * @param international
 * @param bacs
 */

data class ProcessorNumber(

    @field:JsonProperty("ach")
    val ach: NumbersACHNullable? = null,

    @field:JsonProperty("eft")
    val eft: NumbersEFTNullable? = null,

    @field:JsonProperty("international")
    val international: NumbersInternationalNullable? = null,

    @field:JsonProperty("bacs")
    val bacs: NumbersBACSNullable? = null

) : kotlin.collections.HashMap<String, kotlin.Any>()

