/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * A representation of the status health of a request type. Auth requests, Balance requests, Identity requests, Investments requests, Liabilities requests, Transactions updates, Investments updates, Liabilities updates, and Item logins each have their own status object.
 *
 * @param status This field is deprecated in favor of the `breakdown` object, which provides more granular institution health data.  `HEALTHY`: the majority of requests are successful `DEGRADED`: only some requests are successful `DOWN`: all requests are failing
 * @param lastStatusChange [ISO 8601](https://wikipedia.org/wiki/ISO_8601) formatted timestamp of the last status change for the institution.
 * @param breakdown
 */

data class ProductStatus(

    /* This field is deprecated in favor of the `breakdown` object, which provides more granular institution health data.  `HEALTHY`: the majority of requests are successful `DEGRADED`: only some requests are successful `DOWN`: all requests are failing */
    @field:JsonProperty("status")
    @Deprecated(message = "This property is deprecated.")
    val status: ProductStatus.Status,

    /* [ISO 8601](https://wikipedia.org/wiki/ISO_8601) formatted timestamp of the last status change for the institution.  */
    @field:JsonProperty("last_status_change")
    val lastStatusChange: java.time.OffsetDateTime,

    @field:JsonProperty("breakdown")
    val breakdown: ProductStatusBreakdown

) : kotlin.collections.HashMap<String, kotlin.Any>() {

    /**
     * This field is deprecated in favor of the `breakdown` object, which provides more granular institution health data.  `HEALTHY`: the majority of requests are successful `DEGRADED`: only some requests are successful `DOWN`: all requests are failing
     *
     * Values: hEALTHY,dEGRADED,dOWN
     */
    enum class Status(val value: kotlin.String) {
        @JsonProperty(value = "HEALTHY")
        hEALTHY("HEALTHY"),
        @JsonProperty(value = "DEGRADED")
        dEGRADED("DEGRADED"),
        @JsonProperty(value = "DOWN")
        dOWN("DOWN");
    }
}

