/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * SandboxItemSetVerificationStatusRequest defines the request schema for `/sandbox/item/set_verification_status`
 *
 * @param accessToken The access token associated with the Item data is being requested for.
 * @param accountId The `account_id` of the account whose verification status is to be modified
 * @param verificationStatus The verification status to set the account to.
 * @param clientId Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
 * @param secret Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
 */

data class SandboxItemSetVerificationStatusRequest(

    /* The access token associated with the Item data is being requested for. */
    @field:JsonProperty("access_token")
    val accessToken: kotlin.String,

    /* The `account_id` of the account whose verification status is to be modified */
    @field:JsonProperty("account_id")
    val accountId: kotlin.String,

    /* The verification status to set the account to. */
    @field:JsonProperty("verification_status")
    val verificationStatus: SandboxItemSetVerificationStatusRequest.VerificationStatus,

    /* Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
    @field:JsonProperty("client_id")
    val clientId: kotlin.String? = null,

    /* Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
    @field:JsonProperty("secret")
    val secret: kotlin.String? = null

) {

    /**
     * The verification status to set the account to.
     *
     * Values: automaticallyVerified,verificationExpired
     */
    enum class VerificationStatus(val value: kotlin.String) {
        @JsonProperty(value = "automatically_verified")
        automaticallyVerified("automatically_verified"),
        @JsonProperty(value = "verification_expired")
        verificationExpired("verification_expired");
    }
}

