/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Analysis information describing why a screening hit matched the provided user information
 *
 * @param searchTermsVersion The version of the screening's `search_terms` that were compared when the screening hit was added. screening hits are immutable once they have been reviewed. If changes are detected due to updates to the screening's `search_terms`, the associated program, or the list's source data prior to review, the screening hit will be updated to reflect those changes.
 * @param datesOfBirth
 * @param documents
 * @param locations
 * @param names
 */

data class ScreeningHitAnalysis(

    /* The version of the screening's `search_terms` that were compared when the screening hit was added. screening hits are immutable once they have been reviewed. If changes are detected due to updates to the screening's `search_terms`, the associated program, or the list's source data prior to review, the screening hit will be updated to reflect those changes. */
    @field:JsonProperty("search_terms_version")
    val searchTermsVersion: java.math.BigDecimal,

    @field:JsonProperty("dates_of_birth")
    val datesOfBirth: MatchSummaryCode? = null,

    @field:JsonProperty("documents")
    val documents: MatchSummaryCode? = null,

    @field:JsonProperty("locations")
    val locations: MatchSummaryCode? = null,

    @field:JsonProperty("names")
    val names: MatchSummaryCode? = null

)

