/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * No documentation available
 *
 * @param vendorOrderIdentifier A string that uniquely identifies a type of order Verification of Asset.
 * @param serviceProductFulfillmentIdentifier
 */

data class ServiceProductFulfillmentDetail(

    /* A string that uniquely identifies a type of order Verification of Asset. */
    @field:JsonProperty("VendorOrderIdentifier")
    val vendorOrderIdentifier: kotlin.String?,

    @field:JsonProperty("ServiceProductFulfillmentIdentifier")
    val serviceProductFulfillmentIdentifier: ServiceProductFulfillmentIdentifier

) : kotlin.collections.HashMap<String, kotlin.Any>()

