/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Data about an official document used to report the user's income to the IRS.
 *
 * @param documentType The type of tax document. Currently, the only supported value is `w2`.
 * @param docId An identifier of the document referenced by the document metadata.
 * @param w2
 */

data class Taxform(

    /* The type of tax document. Currently, the only supported value is `w2`. */
    @field:JsonProperty("document_type")
    val documentType: kotlin.String,

    /* An identifier of the document referenced by the document metadata. */
    @field:JsonProperty("doc_id")
    val docId: kotlin.String? = null,

    @field:JsonProperty("w2")
    val w2: W2? = null

) : kotlin.collections.HashMap<String, kotlin.Any>()

