/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * A representation of transactions rule details.
 *
 * @param `field`
 * @param type
 * @param query For TRANSACTION_ID field, provide transaction_id. For NAME field, provide a string pattern.
 */

data class TransactionsRuleDetails(

    @field:JsonProperty("field")
    val `field`: TransactionsRuleField,

    @field:JsonProperty("type")
    val type: TransactionsRuleType,

    /* For TRANSACTION_ID field, provide transaction_id. For NAME field, provide a string pattern.  */
    @field:JsonProperty("query")
    val query: kotlin.String

)

