/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The address associated with the account holder.
 *
 * @param street The street number and name (i.e., \"100 Market St.\").
 * @param city Ex. \"San Francisco\"
 * @param region The state or province (e.g., \"CA\").
 * @param postalCode The postal code (e.g., \"94103\").
 * @param country A two-letter country code (e.g., \"US\").
 */

data class TransferUserAddressInResponse(

    /* The street number and name (i.e., \"100 Market St.\"). */
    @field:JsonProperty("street")
    val street: kotlin.String?,

    /* Ex. \"San Francisco\" */
    @field:JsonProperty("city")
    val city: kotlin.String?,

    /* The state or province (e.g., \"CA\"). */
    @field:JsonProperty("region")
    val region: kotlin.String?,

    /* The postal code (e.g., \"94103\"). */
    @field:JsonProperty("postal_code")
    val postalCode: kotlin.String?,

    /* A two-letter country code (e.g., \"US\"). */
    @field:JsonProperty("country")
    val country: kotlin.String?

) : kotlin.collections.HashMap<String, kotlin.Any>()

