/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Represents a return on a Guaranteed ACH transfer that is included in the specified repayment.
 *
 * @param transferId The unique identifier of the guaranteed transfer that was returned.
 * @param eventId The unique identifier of the corresponding `returned` transfer event.
 * @param amount The value of the returned transfer.
 * @param isoCurrencyCode The currency of the repayment, e.g. \"USD\".
 */

data class TransferRepaymentReturn(

    /* The unique identifier of the guaranteed transfer that was returned. */
    @field:JsonProperty("transfer_id")
    val transferId: kotlin.String,

    /* The unique identifier of the corresponding `returned` transfer event. */
    @field:JsonProperty("event_id")
    val eventId: kotlin.Int,

    /* The value of the returned transfer. */
    @field:JsonProperty("amount")
    val amount: kotlin.String,

    /* The currency of the repayment, e.g. \"USD\". */
    @field:JsonProperty("iso_currency_code")
    val isoCurrencyCode: kotlin.String

) : kotlin.collections.HashMap<String, kotlin.Any>()

