/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.164.8
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.plaidApi.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * An object representing the e-wallet balance
 *
 * @param isoCurrencyCode The ISO-4217 currency code of the balance
 * @param current The total amount of funds in the account
 */

data class WalletBalance(

    /* The ISO-4217 currency code of the balance */
    @field:JsonProperty("iso_currency_code")
    val isoCurrencyCode: kotlin.String,

    /* The total amount of funds in the account */
    @field:JsonProperty("current")
    val current: kotlin.Double

) : kotlin.collections.HashMap<String, kotlin.Any>()

