/**
 * Firefly III API v1.5.6
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.fireflyApi.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param transactionGroupId Transaction group ID of the paid bill.
 * @param transactionJournalId Transaction journal ID of the paid bill.
 * @param date Date the bill was paid.
 */

data class BillPaidDatesInner(

    /* Transaction group ID of the paid bill. */
    @field:JsonProperty("transaction_group_id")
    val transactionGroupId: kotlin.String? = null,

    /* Transaction journal ID of the paid bill. */
    @field:JsonProperty("transaction_journal_id")
    val transactionJournalId: kotlin.String? = null,

    /* Date the bill was paid. */
    @field:JsonProperty("date")
    val date: java.time.OffsetDateTime? = null

)

