/**
 * Firefly III API v1.5.6
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.fireflyApi.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param enabled If the currency is enabled
 * @param default If the currency must be the default for the user. You can only submit TRUE.
 * @param code The currency code
 * @param name The currency name
 * @param symbol The currency symbol
 * @param decimalPlaces How many decimals to use when displaying this currency. Between 0 and 16.
 */

data class CurrencyUpdate(

    /* If the currency is enabled */
    @field:JsonProperty("enabled")
    val enabled: kotlin.Boolean? = null,

    /* If the currency must be the default for the user. You can only submit TRUE. */
    @field:JsonProperty("default")
    val default: CurrencyUpdate.Default? = null,

    /* The currency code */
    @field:JsonProperty("code")
    val code: kotlin.String? = null,

    /* The currency name */
    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    /* The currency symbol */
    @field:JsonProperty("symbol")
    val symbol: kotlin.String? = null,

    /* How many decimals to use when displaying this currency. Between 0 and 16. */
    @field:JsonProperty("decimal_places")
    val decimalPlaces: kotlin.Int? = null

) {

    /**
     * If the currency must be the default for the user. You can only submit TRUE.
     *
     * Values: `true`
     */
    enum class Default(val value: kotlin.Boolean) {
        @JsonProperty(value = "", required = true, namespace = "")
        `true`(true);
    }
}

