/**
 * Firefly III API v1.5.6
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.fireflyApi.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param type
 * @param `value` The accompanying value the trigger responds to. This value is often mandatory, but this depends on the trigger.
 * @param order Order of the trigger
 * @param active If the trigger is active. Defaults to true.
 * @param stopProcessing When true, other triggers will not be checked if this trigger was triggered. Defaults to false.
 */

data class RuleTriggerStore(

    @field:JsonProperty("type")
    val type: RuleTriggerKeyword,

    /* The accompanying value the trigger responds to. This value is often mandatory, but this depends on the trigger. */
    @field:JsonProperty("value")
    val `value`: kotlin.String,

    /* Order of the trigger */
    @field:JsonProperty("order")
    val order: kotlin.Int? = null,

    /* If the trigger is active. Defaults to true. */
    @field:JsonProperty("active")
    val active: kotlin.Boolean? = true,

    /* When true, other triggers will not be checked if this trigger was triggered. Defaults to false. */
    @field:JsonProperty("stop_processing")
    val stopProcessing: kotlin.Boolean? = false

)

