/**
 * Firefly III API v1.5.6
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.djvk.fireflyPlaidConnector2.fireflyApi.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param linkTypeId The link type ID to use. Use this field OR use the link_type_name field.
 * @param linkTypeName The link type name to use. Use this field OR use the link_type_id field.
 * @param inwardId The inward transaction transaction_journal_id for the link. This becomes the 'is paid by' transaction of the set.
 * @param outwardId The outward transaction transaction_journal_id for the link. This becomes the 'pays for' transaction of the set.
 * @param notes Optional. Some notes. If you submit an empty string the current notes will be removed
 */

data class TransactionLinkUpdate(

    /* The link type ID to use. Use this field OR use the link_type_name field. */
    @field:JsonProperty("link_type_id")
    val linkTypeId: kotlin.String? = null,

    /* The link type name to use. Use this field OR use the link_type_id field. */
    @field:JsonProperty("link_type_name")
    val linkTypeName: kotlin.String? = null,

    /* The inward transaction transaction_journal_id for the link. This becomes the 'is paid by' transaction of the set. */
    @field:JsonProperty("inward_id")
    val inwardId: kotlin.String? = null,

    /* The outward transaction transaction_journal_id for the link. This becomes the 'pays for' transaction of the set. */
    @field:JsonProperty("outward_id")
    val outwardId: kotlin.String? = null,

    /* Optional. Some notes. If you submit an empty string the current notes will be removed */
    @field:JsonProperty("notes")
    val notes: kotlin.String? = null

)

